version: "3.1"

services:
  # mysql:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   volumes:
  #     - ./init:/docker-entrypoint-initdb.d
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 1234
  #   ports:
  #     - 3306:3306
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
